### PR TITLE
fix: Unknown type "undefined" when using generics without base type

### LINKED ISSUE #1977: Error: Unknown type "undefined"
The generator throws this issue when running inside the code below:

```ts
import stringify from "safe-stable-stringify";

export function intersectionOfArrays<T>(a: T[], b: T[]): T[] {
    const output: T[] = [];
    const inA: Set<string> = new Set(a.map((item: T) => stringify(item!)));
    for (const value of b) {
        if (inA.has(stringify(value!))) {
            output.push(value);
        }
    }
    return output;
}
```

Stack trace from the branch `arthur/oclif`:

```
Error: Unknown type "undefined"
    at ChainTypeFormatter.getTypeFormatter (/home/hzk/dev/ts-json-schema-generator/src/ChainTypeFormatter.ts:32:15)
    at ChainTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/ChainTypeFormatter.ts:22:21)
    at CircularReferenceTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/CircularReferenceTypeFormatter.ts:32:50)
    at ArrayTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/TypeFormatter/ArrayTypeFormatter.ts:20:40)
    at ChainTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/ChainTypeFormatter.ts:22:44)
    at CircularReferenceTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/CircularReferenceTypeFormatter.ts:32:50)
    at /home/hzk/dev/ts-json-schema-generator/src/TypeFormatter/ObjectTypeFormatter.ts:54:59
    at Array.reduce (<anonymous>)
    at ObjectTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/TypeFormatter/ObjectTypeFormatter.ts:48:44)
    at ChainTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/ChainTypeFormatter.ts:22:44)
    at CircularReferenceTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/CircularReferenceTypeFormatter.ts:32:50)
    at FunctionTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/TypeFormatter/FunctionTypeFormatter.ts:37:52)
    at ChainTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/ChainTypeFormatter.ts:22:44)
    at CircularReferenceTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/CircularReferenceTypeFormatter.ts:32:50)
    at DefinitionTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/TypeFormatter/DefinitionTypeFormatter.ts:22:62)
    at ChainTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/ChainTypeFormatter.ts:22:44)
    at CircularReferenceTypeFormatter.getChildren (/home/hzk/dev/ts-json-schema-generator/src/CircularReferenceTypeFormatter.ts:32:50)
    at SchemaGenerator.appendRootChildDefinitions (/home/hzk/dev/ts-json-schema-generator/src/SchemaGenerator.ts:93:14)
    at SchemaGenerator.createSchemaFromNodes (/home/hzk/dev/ts-json-schema-generator/src/SchemaGenerator.ts:41:18)
    at SchemaGenerator.createSchema (/home/hzk/dev/ts-json-schema-generator/src/SchemaGenerator.ts:28:26)
    at Generate.run (/home/hzk/dev/ts-json-schema-generator/commands/generate.ts:166:53)
    at async Generate._run (/home/hzk/dev/ts-json-schema-generator/node_modules/.pnpm/@oclif+core@3.26.6/node_modules/@oclif/core/lib/command.js:311:22)
    at async Config.runCommand (/home/hzk/dev/ts-json-schema-generator/node_modules/.pnpm/@oclif+core@3.26.6/node_modules/@oclif/core/lib/config/config.js:433:25)
    at async run (/home/hzk/dev/ts-json-schema-generator/node_modules/.pnpm/@oclif+core@3.26.6/node_modules/@oclif/core/lib/main.js:92:16)
```

### PR DESCRIPTION
**Pull request by arthurfiorette**
closes #1977

<details>
  <summary>📦 Published PR as canary version: <code>2.2.1--canary.1978.156da78.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install ts-json-schema-generator@2.2.1--canary.1978.156da78.0
  # or 
  yarn add ts-json-schema-generator@2.2.1--canary.1978.156da78.0
  ```
</details>

# Version

Published prerelease version: `v2.3.0-next.4`

<details>
  <summary>Changelog</summary>

  #### 🚀 Enhancement
  
  - feat: get version from package.json [#1979](https://github.com/vega/ts-json-schema-generator/pull/1979) ([@domoritz](https://github.com/domoritz))
  - fix: revert back to commons js [#1975](https://github.com/vega/ts-json-schema-generator/pull/1975) ([@arthurfiorette](https://github.com/arthurfiorette))
  - fix: remove ts-expose-types temporarily [#1968](https://github.com/vega/ts-json-schema-generator/pull/1968) ([@arthurfiorette](https://github.com/arthurfiorette))
  - Added diagnostics to all errors [#1963](https://github.com/vega/ts-json-schema-generator/pull/1963) ([@arthurfiorette](https://github.com/arthurfiorette))
  
  #### 🐛 Bug Fix
  
  - fix: Unknown type "undefined" when using generics without base type [#1978](https://github.com/vega/ts-json-schema-generator/pull/1978) ([@arthurfiorette](https://github.com/arthurfiorette))
  
  #### 🔩 Dependency Updates
  
  - chore(deps-dev): bump eslint from 9.2.0 to 9.3.0 [#1970](https://github.com/vega/ts-json-schema-generator/pull/1970) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump ajv from 8.13.0 to 8.14.0 [#1971](https://github.com/vega/ts-json-schema-generator/pull/1971) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump typescript-eslint from 7.8.0 to 7.10.0 [#1972](https://github.com/vega/ts-json-schema-generator/pull/1972) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  
  #### Authors: 3
  
  - [@dependabot[bot]](https://github.com/dependabot[bot])
  - Arthur Fiorette ([@arthurfiorette](https://github.com/arthurfiorette))
  - Dominik Moritz ([@domoritz](https://github.com/domoritz))
</details>

### CODE REVIEW

**Comment by arthurfiorette** [comment]
The problem is surely deeper than that, since its returning undefined to a type that should always be defined, but this is a temp fix until I have time to deeper investigate this issue.

File: src/NodeParser/ArrayNodeParser.ts [hunk 1]
```diff
@@ -13,6 +14,12 @@ export class ArrayNodeParser implements SubNodeParser {
 
     public createType(node: ts.ArrayTypeNode, context: Context): BaseType {
         const type = this.childNodeParser.createType(node.elementType, context);
+
+        // Generics without `extends` or `defaults` cannot be resolved, so we fallback to `any`
+        if (!type) {
```
Comment (domoritz) [inline src/NodeParser/ArrayNodeParser.ts]: Just add ?? AnyType() above?

**Review by domoritz — CHANGES_REQUESTED** [review]
