### PR TITLE
fix: fully unwrap union aliases in mapped keys to avoid generating incorrect additionalProperties

### LINKED ISSUE #2231: `Pick` with union of unions of literals generates wrong `additionalProperties`.
Just to clarify what's not covered in this PR: the fix only dereferences the top-level union keys, but not nested aliases.

For example:
```ts
SomeInterface {
  a: number;
  b: string;
  c: boolean;
}

type AB = "a" | "b";
type C = "c";

export type Test = Pick<SomeInterface, AB | C>;
```
still produces unexpected "additionalProperties"

_Originally posted by @alexchexes in https://github.com/vega/ts-json-schema-generator/issues/2230#issuecomment-2800225354_

### PR DESCRIPTION
**Pull request by alexchexes**
Closes #2231

# Version

Published prerelease version: `v2.4.1-next.1`

<details>
  <summary>Changelog</summary>

  :tada: This release contains work from a new contributor! :tada:
  
  Thank you, Alex ([@alexchexes](https://github.com/alexchexes)), for all your work!
  
  #### 🐛 Bug Fix
  
  - fix: fully unwrap union aliases in mapped keys to avoid generating incorrect additionalProperties [#2232](https://github.com/vega/ts-json-schema-generator/pull/2232) ([@alexchexes](https://github.com/alexchexes))
  - fix: avoid incorrect additionalProperties for Pick<..., AliasLiteralUnion> [#2230](https://github.com/vega/ts-json-schema-generator/pull/2230) ([@alexchexes](https://github.com/alexchexes))
  
  #### 🔩 Dependency Updates
  
  - chore(deps-dev): bump eslint-config-prettier from 10.1.2 to 10.1.5 [#2249](https://github.com/vega/ts-json-schema-generator/pull/2249) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump typescript-eslint from 8.31.0 to 8.32.0 [#2250](https://github.com/vega/ts-json-schema-generator/pull/2250) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump tsx from 4.19.3 to 4.19.4 [#2251](https://github.com/vega/ts-json-schema-generator/pull/2251) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump eslint from 9.25.1 to 9.26.0 [#2252](https://github.com/vega/ts-json-schema-generator/pull/2252) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump eslint-plugin-prettier from 5.2.6 to 5.4.0 [#2253](https://github.com/vega/ts-json-schema-generator/pull/2253) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump @babel/preset-typescript from 7.27.0 to 7.27.1 [#2244](https://github.com/vega/ts-json-schema-generator/pull/2244) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump @eslint/js from 9.25.1 to 9.26.0 [#2245](https://github.com/vega/ts-json-schema-generator/pull/2245) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump @babel/preset-env from 7.26.9 to 7.27.1 [#2246](https://github.com/vega/ts-json-schema-generator/pull/2246) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump @babel/core from 7.26.10 to 7.27.1 [#2247](https://github.com/vega/ts-json-schema-generator/pull/2247) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump @types/node from 22.15.2 to 22.15.3 [#2248](https://github.com/vega/ts-json-schema-generator/pull/2248) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump @types/node from 22.14.1 to 22.15.2 [#2239](https://github.com/vega/ts-json-schema-generator/pull/2239) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps): bump glob from 11.0.1 to 11.0.2 [#2240](https://github.com/vega/ts-json-schema-generator/pull/2240) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump eslint from 9.25.0 to 9.25.1 [#2242](https://github.com/vega/ts-json-schema-generator/pull/2242) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump typescript-eslint from 8.30.1 to 8.31.0 [#2243](https://github.com/vega/ts-json-schema-generator/pull/2243) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump typescript-eslint from 8.29.1 to 8.30.1 [#2235](https://github.com/vega/ts-json-schema-generator/pull/2235) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump @eslint/js from 9.24.0 to 9.25.0 [#2236](https://github.com/vega/ts-json-schema-generator/pull/2236) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump eslint from 9.24.0 to 9.25.0 [#2237](https://github.com/vega/ts-json-schema-generator/pull/2237) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump @types/node from 22.14.0 to 22.14.1 [#2225](https://github.com/vega/ts-json-schema-generator/pull/2225) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump typescript-eslint from 8.29.0 to 8.29.1 [#2226](https://github.com/vega/ts-json-schema-generator/pull/2226) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump eslint-config-prettier from 10.1.1 to 10.1.2 [#2227](https://github.com/vega/ts-json-schema-generator/pull/2227) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  - chore(deps-dev): bump eslint from 9.23.0 to 9.24.0 [#2228](https://github.com/vega/ts-json-schema-generator/pull/2228) ([@dependabot[bot]](https://github.com/dependabot[bot]))
  
  #### Authors: 2
  
  - [@dependabot[bot]](https://github.com/dependabot[bot])
  - Alex ([@alexchexes](https://github.com/alexchexes))
</details>

### CODE REVIEW

**Review by arthurfiorette — APPROVED** [review]
LGTM

File: test/valid-data/type-mapped-pick-union-alias/main.ts [hunk 1]
```diff
@@ -1,9 +1,19 @@
...
+type A = "a";
+type B = "b";
+type C = "c";
+type D = "d";
+type E = "e";
 
-export type PickAliasedLiteralUnion = Pick<SomeInterface, KeyFoo | KeyBar>;
+type AB = A | B;
+type ABC = AB | C;
+type ABCD = ABC | D;
```
Comment (domoritz) [inline test/valid-data/type-mapped-pick-union-alias/main.ts:17]: What happens if we export any of these types? Can we still preserve the alias?

Comment (arthurfiorette) [reply test/valid-data/type-mapped-pick-union-alias/main.ts:17]: nice catch

Comment (arthurfiorette) [reply test/valid-data/type-mapped-pick-union-alias/main.ts:17]: @alexchexes, please create a new test with those exported types so we can guarantee both behaviors

**Review by arthurfiorette — CHANGES_REQUESTED** [review]

File: test/valid-data/type-mapped-pick-union-alias/main.ts (hunk 1 above)
Comment (alexchexes) [reply test/valid-data/type-mapped-pick-union-alias/main.ts:17]: Done! Added a new test case `type-mapped-exported-aliases` that exports those aliases and verifies they are preserved in the schema. `additionalProperties` is also correctly set to `false` in the final object

**Review by arthurfiorette — APPROVED** [review]

**Comment by arthurfiorette** [comment]
Tested it locally and also worked as expected. Thanks!
